import path from 'node:path';

/** The layout from §4. Every path in the tool resolves through here. */
export const VAULT = {
	meta: '.litrpg',
	config: '.litrpg/config.json',
	cache: '.litrpg/cache.json',
	raw: 'raw',
	system: 'system',
	/**
	 * One page per character system (§3). The legacy `system/*.md` files still
	 * load, as the system named `system`, so a vault written before systems were
	 * a primitive needs no migration.
	 */
	systems: 'systems',
	/** Setting descriptors and the idiom reference (§3.1). */
	settingFile: 'system/system.md',
	/** Per-vault profile override; author edits win over the shipped profile. */
	idiom: 'system/idiom.md',
	stats: 'system/stats.md',
	curves: 'system/curves.md',
	formulas: 'system/formulas.md',
	skills: 'system/skills.md',
	timeline: 'timeline',
	/**
	 * One page per moment (§5). `timeline/world-events.md` still loads, as a list
	 * of moments, so a vault written before they were pages needs no migration.
	 */
	moments: 'timeline/moments',
	/** The pre-moments single-file list. Read, never written. */
	legacyMoments: 'timeline/world-events.md',
	arcs: 'timeline/arcs',
	characters: 'characters',
	themes: 'themes',
	places: 'places',
	factions: 'factions',
	/** Things characters use to achieve outcomes (§3): spells, rifles, instruments. */
	artifacts: 'artifacts',
	situations: 'situations',
	inbox: 'situations/inbox',
	/** Cuts in the replay sequence (§6 step 6); membership is derived, not stored. */
	chapters: 'chapters',
	/** Derived cross-reference of the corpus; regenerated by `/wiki build`. */
	wiki: 'wiki',
	ledger: 'ledger',
	state: 'ledger/state.md',
	openQuestions: 'ledger/open-questions.md',
	index: 'index.md',
	log: 'log.md',
	/** Derived like `ledger/state.md`: assembled by `/export`, never hand-edited. */
	manuscript: 'manuscript.md',
} as const;

/** Directories `/init` creates. Order matters only for readable output. */
export const VAULT_DIRECTORIES: readonly string[] = [
	VAULT.meta,
	VAULT.raw,
	VAULT.system,
	VAULT.systems,
	VAULT.timeline,
	VAULT.moments,
	VAULT.arcs,
	VAULT.characters,
	VAULT.themes,
	VAULT.places,
	VAULT.factions,
	VAULT.artifacts,
	VAULT.situations,
	VAULT.inbox,
	VAULT.chapters,
	VAULT.wiki,
	VAULT.ledger,
];

export function resolve(root: string, ...segments: string[]): string {
	return path.join(root, ...segments);
}
