import path from 'node:path';

/**
 * The layout. Every path in the tool resolves through here.
 *
 * Three top-level directories say who owns what, which is the whole reason
 * they are named the way they are:
 *
 * - `raw/` — you write this. Freeform, no schema, one folder per primitive.
 * - `corpus/` — derived from `raw/`. Typed, linked, validated, regenerable.
 * - `setting/` — how this vault reads: its idiom, its formulas, its clock.
 *
 * with `ledger/` and `wiki/` computed from the corpus, and `index.md`,
 * `log.md` and `manuscript.md` at the root because that is where a reader
 * opening the vault in Obsidian will look first.
 *
 * Every path a previous layout used is still read — see `LEGACY_DIRECTORIES`
 * and `LEGACY_FILES`. Nothing writes to one.
 */
export const VAULT = {
	meta: '.litrpg',
	config: '.litrpg/config.json',
	cache: '.litrpg/cache.json',

	/** What the author writes. One folder per primitive, plus interviews. */
	raw: 'raw',

	/**
	 * What the tool derives. Everything under here cites the note it came from
	 * and can be rebuilt by `/ingest`, which is what makes it safe to delete.
	 */
	corpus: 'corpus',
	characters: 'corpus/characters',
	themes: 'corpus/themes',
	places: 'corpus/places',
	factions: 'corpus/factions',
	/** Things characters use to achieve outcomes (§3): spells, rifles, instruments. */
	artifacts: 'corpus/artifacts',
	/** What a character can do, as opposed to what they carry (§3). */
	skills: 'corpus/skills',
	situations: 'corpus/situations',
	/** One page per character system (§3). */
	systems: 'corpus/systems',
	/** One page per moment (§5). */
	moments: 'corpus/moments',
	arcs: 'corpus/arcs',
	/** Cuts in the replay sequence; membership is derived, not stored. */
	chapters: 'corpus/chapters',

	/**
	 * How this vault reads, as opposed to what is in it.
	 *
	 * Was `system/`, one letter from `systems/` and meaning something entirely
	 * different — which is why the scaffold's own system had to be called
	 * `system-01`: `[[system]]` was already taken by the setting page.
	 */
	setting: 'setting',
	/** Setting descriptors and the idiom reference (§3.1). */
	settingFile: 'setting/setting.md',
	/** Per-vault profile override; author edits win over the shipped profile. */
	idiom: 'setting/idiom.md',
	/** Unscoped formulas, reachable from every system. */
	formulas: 'setting/formulas.md',
	/** The clock binding: raw seconds, a Gregorian epoch, or a custom calendar. */
	time: 'setting/time.md',

	/** Derived cross-reference of the corpus; regenerated by `/wiki build`. */
	wiki: 'wiki',
	ledger: 'ledger',
	state: 'ledger/state.md',
	openQuestions: 'ledger/open-questions.md',
	index: 'index.md',
	log: 'log.md',
	/** Derived like `ledger/state.md`: assembled by `/export`, never hand-edited. */
	manuscript: 'manuscript.md',

	// --- read, never written -------------------------------------------------

	/** The pre-`setting/` home of the descriptors, idiom and formulas. */
	legacySetting: 'system',
	stats: 'system/stats.md',
	curves: 'system/curves.md',
	legacySkills: 'system/skills.md',
	legacyFormulas: 'system/formulas.md',
	legacySettingFile: 'system/system.md',
	legacyIdiom: 'system/idiom.md',
	/** The pre-moments single-file list. */
	legacyMoments: 'timeline/world-events.md',
	legacyTime: 'timeline/time.md',
	/**
	 * The pre-D19 home for a scene with no arc. It encoded in the filesystem
	 * what `arc:` already says, and a second legal home for one id is how one
	 * situation came to exist twice.
	 */
	inbox: 'situations/inbox',
} as const;

/** Directories `/init` creates. Order matters only for readable output. */
/**
 * The primitive folders under `raw/`, one per kind.
 *
 * Declared here rather than in `ingest/` so `scaffold.ts` can create them
 * without importing the ingest module and everything it pulls in. `ingest/`
 * asserts against this list, so the two cannot drift.
 */
export const RAW_KINDS: readonly string[] = [
	'arcs',
	'artifacts',
	'chapters',
	'characters',
	'factions',
	'moments',
	'places',
	'situations',
	'skills',
	'systems',
	'themes',
];

export const RAW_DIRECTORIES: readonly string[] = RAW_KINDS.map(
	kind => `${VAULT.raw}/${kind}`,
);

/**
 * Every corpus directory, in the order a reader would want them listed.
 *
 * One list rather than nine call sites, so adding a primitive cannot leave a
 * directory that `/init` creates and nothing walks, or the reverse.
 */
export const CORPUS_DIRECTORIES: readonly string[] = [
	VAULT.systems,
	VAULT.moments,
	VAULT.arcs,
	VAULT.characters,
	VAULT.themes,
	VAULT.places,
	VAULT.factions,
	VAULT.artifacts,
	VAULT.skills,
	VAULT.situations,
	VAULT.chapters,
];

export const VAULT_DIRECTORIES: readonly string[] = [
	VAULT.meta,
	VAULT.raw,
	...RAW_DIRECTORIES,
	// Where interviews land. Not a primitive folder — a transcript is a source
	// that touches several kinds at once — but a real place things are written,
	// and its absence was indistinguishable from being in the wrong vault.
	`${VAULT.raw}/interviews`,
	VAULT.setting,
	VAULT.corpus,
	...CORPUS_DIRECTORIES,
	VAULT.wiki,
	VAULT.ledger,
];

/**
 * Where a directory used to live, and where its contents belong now.
 *
 * Read, never written. A vault written before `corpus/` and `setting/` keeps
 * loading exactly as it did — the loader walks both, the canonical page wins a
 * clash, and `/lint` reports the old location so the vault empties rather than
 * staying half-moved forever. This is the same contract `situations/inbox/`
 * has had since D19; the layout change simply made it apply to everything.
 */
export const LEGACY_DIRECTORIES: Readonly<Record<string, string>> = {
	characters: VAULT.characters,
	themes: VAULT.themes,
	places: VAULT.places,
	factions: VAULT.factions,
	artifacts: VAULT.artifacts,
	situations: VAULT.situations,
	'situations/inbox': VAULT.situations,
	systems: VAULT.systems,
	'timeline/moments': VAULT.moments,
	'timeline/arcs': VAULT.arcs,
	chapters: VAULT.chapters,
	system: VAULT.setting,
};

/**
 * Files from a layout litfire has moved on from, still read so no vault breaks.
 *
 * Each has a modern equivalent that is now the only thing written. Naming them
 * here lets `/lint` report a vault that still has one without the checks having
 * to know how the loader works.
 */
export const LEGACY_FILES: Readonly<Record<string, string>> = {
	'system/stats.md': 'corpus/systems/<id>.md',
	'system/skills.md': 'corpus/systems/<id>.md',
	'system/curves.md': 'corpus/systems/<id>.md',
	'system/system.md': VAULT.settingFile,
	'system/idiom.md': VAULT.idiom,
	'system/formulas.md': VAULT.formulas,
	'timeline/world-events.md': 'corpus/moments/<id>.md',
	'timeline/time.md': VAULT.time,
};

/**
 * Every directory a kind's pages may be sitting in, canonical home first.
 *
 * Order is the contract: the first file to claim an id wins, so a page already
 * moved beats the copy left behind. Lives here rather than in the loader
 * because the loader is not the only thing that has to find a page — the wiki
 * reads author prose straight off disk, and a reader that knows only the
 * canonical home renders an empty page for every vault that has not migrated.
 */
export function homesOf(canonical: string): string[] {
	return [
		canonical,
		...Object.entries(LEGACY_DIRECTORIES)
			.filter(([, to]) => to === canonical)
			.map(([from]) => from),
	];
}

export function resolve(root: string, ...segments: string[]): string {
	return path.join(root, ...segments);
}
