import path from 'node:path';

/** The layout from §4. Every path in the tool resolves through here. */
export const VAULT = {
	meta: '.litrpg',
	config: '.litrpg/config.json',
	cache: '.litrpg/cache.json',
	raw: 'raw',
	system: 'system',
	/**
	 * One page per character system (§3). The legacy `system/*.md` files still
	 * load, as the system named `system`, so a vault written before systems were
	 * a primitive needs no migration.
	 */
	systems: 'systems',
	/** Setting descriptors and the idiom reference (§3.1). */
	settingFile: 'system/system.md',
	/** Per-vault profile override; author edits win over the shipped profile. */
	idiom: 'system/idiom.md',
	stats: 'system/stats.md',
	curves: 'system/curves.md',
	formulas: 'system/formulas.md',
	skills: 'system/skills.md',
	timeline: 'timeline',
	/**
	 * One page per moment (§5). `timeline/world-events.md` still loads, as a list
	 * of moments, so a vault written before they were pages needs no migration.
	 */
	moments: 'timeline/moments',
	time: 'timeline/time.md',
	/** The pre-moments single-file list. Read, never written. */
	legacyMoments: 'timeline/world-events.md',
	arcs: 'timeline/arcs',
	characters: 'characters',
	themes: 'themes',
	places: 'places',
	factions: 'factions',
	/** Things characters use to achieve outcomes (§3): spells, rifles, instruments. */
	artifacts: 'artifacts',
	situations: 'situations',
	/**
	 * The pre-D19 home for a scene with no arc. Read, never written, and never
	 * created: it encoded in the filesystem what `arc:` already says, and a
	 * second legal home for one id is how one situation came to exist twice.
	 */
	inbox: 'situations/inbox',
	/** Cuts in the replay sequence (§6 step 6); membership is derived, not stored. */
	chapters: 'chapters',
	/** Derived cross-reference of the corpus; regenerated by `/wiki build`. */
	wiki: 'wiki',
	ledger: 'ledger',
	state: 'ledger/state.md',
	openQuestions: 'ledger/open-questions.md',
	index: 'index.md',
	log: 'log.md',
	/** Derived like `ledger/state.md`: assembled by `/export`, never hand-edited. */
	manuscript: 'manuscript.md',
} as const;

/** Directories `/init` creates. Order matters only for readable output. */
/**
 * The primitive folders under `raw/`, one per kind.
 *
 * Declared here rather than in `ingest/` so `scaffold.ts` can create them
 * without importing the ingest module and everything it pulls in. `ingest/`
 * asserts against this list, so the two cannot drift.
 */
export const RAW_KINDS: readonly string[] = [
	'characters',
	'moments',
	'places',
	'situations',
	'systems',
	'arcs',
	'factions',
	'artifacts',
	'themes',
];

export const RAW_DIRECTORIES: readonly string[] = RAW_KINDS.map(
	kind => `${VAULT.raw}/${kind}`,
);

export const VAULT_DIRECTORIES: readonly string[] = [
	VAULT.meta,
	VAULT.raw,
	...RAW_DIRECTORIES,
	VAULT.system,
	VAULT.systems,
	VAULT.timeline,
	VAULT.moments,
	VAULT.arcs,
	VAULT.characters,
	VAULT.themes,
	VAULT.places,
	VAULT.factions,
	VAULT.artifacts,
	VAULT.situations,
	VAULT.chapters,
	VAULT.wiki,
	VAULT.ledger,
];

/**
 * Files from a layout litfire has moved on from, still read so no vault breaks.
 *
 * Each has a modern equivalent that is now the only thing written: the split
 * `system/*.md` trio became `systems/<id>.md`, and the single-file world-event
 * list became a page per moment. Naming them here lets `/lint` report a vault
 * that still has one without the checks having to know how the loader works.
 */
export const LEGACY_FILES: Readonly<Record<string, string>> = {
	'system/stats.md': 'systems/<id>.md',
	'system/skills.md': 'systems/<id>.md',
	'system/curves.md': 'systems/<id>.md',
	'timeline/world-events.md': 'timeline/moments/<id>.md',
};

export function resolve(root: string, ...segments: string[]): string {
	return path.join(root, ...segments);
}
